version: '3'
services:

  nginx:
    image: {{ nginx_certbot_image }}
    container_name: nginx
    restart: unless-stopped
    networks:
      - monitoring_network
    depends_on:
      - kuma
    ports:
      - '80:80'
      - '443:443'
    environment:
      CERTBOT_EMAIL: {{ certbot_email }}
      SERVER_URL: {{ server_url }}
      USE_LOCAL_CA: {{ certbot_use_local_ca }}
      DEBUG: {{ certbot_debug }}
    volumes:
      - ./nginx_html:/usr/share/nginx/html:ro
      - ./nginx_logs:/logs
      - ./nginx_secrets:/etc/letsencrypt
      - ./nginx_conf.d:/etc/nginx/user_conf.d

  kuma:
    image: louislam/uptime-kuma
    container_name: kuma
    restart: unless-stopped
    depends_on:
      - signal
    networks:
      - monitoring_network
    volumes:
      - {{ docker_monitoring_dir }}/kuma:/app/data

  signal:
    image: bbernhard/signal-cli-rest-api:latest
    container_name: signal
    networks:
      - monitoring_network
    environment:
      - MODE=normal #supported modes: json-rpc, native, normal
      #- AUTO_RECEIVE_SCHEDULE=0 22 * * * #enable this parameter on demand (see description below)
    ports:
      - "8080:8080" #map docker port 8080 to host port 8080.
    volumes:
      - "./signal-cli-config:/home/.local/share/signal-cli" #map "signal-cli-config" folder on host system into docker container. the folder contains the password and cryptographic keys when a new number is registered
 
# volumes:
#   content:
#      driver_opts:
#            type: none
#            device: "{{ docker_monitoring_dir }}/ghost_content"
#            o: bind

networks:
  monitoring_network:
    name: monitoring_network
